[ 2025-04-08 17:01:33,794 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 21 error messgae [Errno 13] Permission denied: 'src/data_set/Thanjavur_forecast_weather.csv'
[ 2025-04-08 17:02:17,725 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 21 error messgae [Errno 13] Permission denied: 'src/data_set/Thanjavur_forecast_weather.csv'
[ 2025-04-08 17:19:42,447 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 21 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744112974, 'localtime': '2025-04-08 17:19'}_forecast_weather.csv"
[ 2025-04-08 17:19:42,451 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 57 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744112974, 'localtime': '2025-04-08 17:19'}_forecast_weather.csv"
[ 2025-04-08 17:23:06,450 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 21 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744112823, 'localtime': '2025-04-08 17:17'}_forecast_weather.csv"
[ 2025-04-08 17:23:06,453 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 58 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744112823, 'localtime': '2025-04-08 17:17'}_forecast_weather.csv"
[ 2025-04-08 17:23:06,454 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 66 error messgae 'Dashboard' object has no attribute 'forecast_data'
[ 2025-04-08 17:23:46,642 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 21 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744112823, 'localtime': '2025-04-08 17:17'}_forecast_weather.csv"
[ 2025-04-08 17:23:46,642 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 58 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744112823, 'localtime': '2025-04-08 17:17'}_forecast_weather.csv"
[ 2025-04-08 17:23:46,643 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 66 error messgae 'Dashboard' object has no attribute 'forecast_data'
[ 2025-04-08 17:29:28,352 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 21 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744113592, 'localtime': '2025-04-08 17:29'}_forecast_weather.csv"
[ 2025-04-08 17:29:28,353 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 58 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744113592, 'localtime': '2025-04-08 17:29'}_forecast_weather.csv"
[ 2025-04-08 17:29:28,354 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 66 error messgae 'Dashboard' object has no attribute 'forecast_data'
[ 2025-04-08 17:33:19,078 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 21 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744114146, 'localtime': '2025-04-08 17:39'}_forecast_weather.csv"
[ 2025-04-08 17:33:19,094 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 58 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744114146, 'localtime': '2025-04-08 17:39'}_forecast_weather.csv"
[ 2025-04-08 17:33:19,094 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 66 error messgae 'Dashboard' object has no attribute 'forecast_data'
[ 2025-04-08 17:37:55,163 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 21 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744113711, 'localtime': '2025-04-08 17:31'}_forecast_weather.csv"
[ 2025-04-08 17:37:55,163 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 58 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744113711, 'localtime': '2025-04-08 17:31'}_forecast_weather.csv"
[ 2025-04-08 17:37:55,163 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 66 error messgae 'Dashboard' object has no attribute 'forecast_data'
[ 2025-04-08 17:40:00,658 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 21 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744113711, 'localtime': '2025-04-08 17:31'}_forecast_weather.csv"
[ 2025-04-08 17:40:00,659 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 58 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744113711, 'localtime': '2025-04-08 17:31'}_forecast_weather.csv"
[ 2025-04-08 17:40:00,660 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 66 error messgae 'Dashboard' object has no attribute 'forecast_data'
[ 2025-04-08 18:48:59,160 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 21 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744117973, 'localtime': '2025-04-08 18:42'}_forecast_weather.csv"
[ 2025-04-08 18:48:59,161 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 58 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744117973, 'localtime': '2025-04-08 18:42'}_forecast_weather.csv"
[ 2025-04-08 18:48:59,162 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 66 error messgae 'Dashboard' object has no attribute 'forecast_data'
[ 2025-04-08 18:49:04,993 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 28 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744117973, 'localtime': '2025-04-08 18:42'}_forecast_weather.csv"
[ 2025-04-08 18:49:04,997 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 60 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744117973, 'localtime': '2025-04-08 18:42'}_forecast_weather.csv"
[ 2025-04-08 18:49:04,997 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 67 error messgae 'Dashboard' object has no attribute 'forecast_data'
[ 2025-04-08 18:49:59,130 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 28 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744117973, 'localtime': '2025-04-08 18:42'}_forecast_weather.csv"
[ 2025-04-08 18:49:59,131 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 60 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744117973, 'localtime': '2025-04-08 18:42'}_forecast_weather.csv"
[ 2025-04-08 18:49:59,131 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 67 error messgae 'Dashboard' object has no attribute 'forecast_data'
[ 2025-04-08 18:52:00,893 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 28 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744118870, 'localtime': '2025-04-08 18:57'}_forecast_weather.csv"
[ 2025-04-08 18:52:00,894 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 60 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744118870, 'localtime': '2025-04-08 18:57'}_forecast_weather.csv"
[ 2025-04-08 18:52:00,895 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 67 error messgae 'Dashboard' object has no attribute 'forecast_data'
[ 2025-04-08 18:52:16,562 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 28 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Ooty', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 11.4, 'lon': 76.7, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744118528, 'localtime': '2025-04-08 18:52'}_forecast_weather.csv"
[ 2025-04-08 18:52:16,565 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 60 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Ooty', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 11.4, 'lon': 76.7, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744118528, 'localtime': '2025-04-08 18:52'}_forecast_weather.csv"
[ 2025-04-08 18:52:16,566 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 67 error messgae 'Dashboard' object has no attribute 'forecast_data'
[ 2025-04-08 18:52:24,516 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 28 error messgae [Errno 2] No such file or directory: "src/data_set/{'name': 'Kanniyakumari', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 8.0761, 'lon': 77.5483, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744118893, 'localtime': '2025-04-08 18:58'}_forecast_weather.csv"
[ 2025-04-08 18:52:24,517 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 60 error messgae [Errno 2] No such file or directory: "src/data_set/{'name': 'Kanniyakumari', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 8.0761, 'lon': 77.5483, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744118893, 'localtime': '2025-04-08 18:58'}_forecast_weather.csv"
[ 2025-04-08 18:52:24,518 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 67 error messgae 'Dashboard' object has no attribute 'forecast_data'
[ 2025-04-08 18:52:47,337 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 28 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744118870, 'localtime': '2025-04-08 18:57'}_forecast_weather.csv"
[ 2025-04-08 18:52:47,339 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 60 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744118870, 'localtime': '2025-04-08 18:57'}_forecast_weather.csv"
[ 2025-04-08 18:52:47,340 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 67 error messgae 'Dashboard' object has no attribute 'forecast_data'
[ 2025-04-08 18:54:41,345 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 28 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744118870, 'localtime': '2025-04-08 18:57'}_forecast_weather.csv"
[ 2025-04-08 18:54:41,347 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 60 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744118870, 'localtime': '2025-04-08 18:57'}_forecast_weather.csv"
[ 2025-04-08 18:54:41,347 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 67 error messgae 'Dashboard' object has no attribute 'forecast_data'
[ 2025-04-08 18:56:03,885 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 28 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744118788, 'localtime': '2025-04-08 18:56'}_forecast_weather.csv"
[ 2025-04-08 18:56:03,886 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 60 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744118788, 'localtime': '2025-04-08 18:56'}_forecast_weather.csv"
[ 2025-04-08 18:56:03,886 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 67 error messgae 'Dashboard' object has no attribute 'forecast_data'
[ 2025-04-08 18:56:18,734 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 28 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744118788, 'localtime': '2025-04-08 18:56'}_forecast_weather.csv"
[ 2025-04-08 18:56:18,736 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 60 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744118788, 'localtime': '2025-04-08 18:56'}_forecast_weather.csv"
[ 2025-04-08 18:56:18,737 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 67 error messgae 'Dashboard' object has no attribute 'forecast_data'
[ 2025-04-08 18:56:49,192 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 28 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744118788, 'localtime': '2025-04-08 18:56'}_forecast_weather.csv"
[ 2025-04-08 18:56:49,193 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 60 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744118788, 'localtime': '2025-04-08 18:56'}_forecast_weather.csv"
[ 2025-04-08 18:56:49,194 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 67 error messgae 'Dashboard' object has no attribute 'forecast_data'
[ 2025-04-08 18:57:34,627 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 28 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744118788, 'localtime': '2025-04-08 18:56'}_forecast_weather.csv"
[ 2025-04-08 18:57:34,628 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 60 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744118788, 'localtime': '2025-04-08 18:56'}_forecast_weather.csv"
[ 2025-04-08 18:57:34,629 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 67 error messgae 'Dashboard' object has no attribute 'forecast_data'
[ 2025-04-08 18:57:44,887 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 28 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744118788, 'localtime': '2025-04-08 18:56'}_forecast_weather.csv"
[ 2025-04-08 18:57:44,889 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 60 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744118788, 'localtime': '2025-04-08 18:56'}_forecast_weather.csv"
[ 2025-04-08 18:57:44,889 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 67 error messgae 'Dashboard' object has no attribute 'forecast_data'
[ 2025-04-08 19:00:13,296 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 29 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744119022, 'localtime': '2025-04-08 19:00'}_forecast_weather.csv"
[ 2025-04-08 19:00:13,296 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 61 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744119022, 'localtime': '2025-04-08 19:00'}_forecast_weather.csv"
[ 2025-04-08 19:00:13,296 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 68 error messgae 'Dashboard' object has no attribute 'forecast_data'
[ 2025-04-08 19:00:49,869 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 50 error messgae name 'output_path' is not defined
[ 2025-04-08 19:03:12,904 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 29 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744119022, 'localtime': '2025-04-08 19:00'}_forecast_weather.csv"
[ 2025-04-08 19:03:12,905 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 61 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744119022, 'localtime': '2025-04-08 19:00'}_forecast_weather.csv"
[ 2025-04-08 19:03:12,906 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 68 error messgae 'Dashboard' object has no attribute 'forecast_data'
[ 2025-04-08 19:03:25,631 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 29 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744119214, 'localtime': '2025-04-08 19:03'}_forecast_weather.csv"
[ 2025-04-08 19:03:25,631 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 61 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744119214, 'localtime': '2025-04-08 19:03'}_forecast_weather.csv"
[ 2025-04-08 19:03:25,631 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 68 error messgae 'Dashboard' object has no attribute 'forecast_data'
[ 2025-04-08 19:04:04,805 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 29 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744119214, 'localtime': '2025-04-08 19:03'}_forecast_weather.csv"
[ 2025-04-08 19:04:04,805 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 61 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744119214, 'localtime': '2025-04-08 19:03'}_forecast_weather.csv"
[ 2025-04-08 19:04:04,805 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 68 error messgae 'Dashboard' object has no attribute 'forecast_data'
[ 2025-04-08 19:32:45,649 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 29 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744120957, 'localtime': '2025-04-08 19:32'}_forecast_weather.csv"
[ 2025-04-08 19:32:45,653 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 61 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744120957, 'localtime': '2025-04-08 19:32'}_forecast_weather.csv"
[ 2025-04-08 19:32:45,655 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 68 error messgae 'Dashboard' object has no attribute 'forecast_data'
[ 2025-04-08 19:33:15,706 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 29 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744120957, 'localtime': '2025-04-08 19:32'}_forecast_weather.csv"
[ 2025-04-08 19:33:15,707 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 61 error messgae [Errno 22] Invalid argument: "src/data_set/{'name': 'Thanjavur', 'region': 'Tamil Nadu', 'country': 'India', 'lat': 10.8, 'lon': 79.15, 'tz_id': 'Asia/Kolkata', 'localtime_epoch': 1744120957, 'localtime': '2025-04-08 19:32'}_forecast_weather.csv"
[ 2025-04-08 19:33:15,707 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\dashboard_details.py on line number 68 error messgae 'Dashboard' object has no attribute 'forecast_data'
